name: Deploy to FTP

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Versión LTS estable recomendada

      # Cache node_modules para acelerar futuras instalaciones
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build the project
        run: npm run build

      - name: Ensure dist directory exists
        run: mkdir -p dist

      - name: Copy .htaccess to dist directory
        run: cp .htaccess dist/.htaccess

      - name: List files in the build directory
        run: ls -la dist

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: '89.116.147.90'
          username: 'u569254146.luisizitax'
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: 'dist/'
